# Copyright (c) 2026 RAKwireless Technology Limited
# Author: sercan.erat@rakwireless.com
# SPDX-License-Identifier: Apache-2.0

"""Shared utilities and base class for RAKwireless west check commands."""

import os
import subprocess
from pathlib import Path

from west import log
from west.commands import WestCommand

# Base ref used for change detection by the check commands.
BASE_REF = "rak-main"

# Repository root, derived from this file's location (extra/rak/) so the
# commands work regardless of the caller's working directory.
REPO_ROOT = Path(__file__).resolve().parents[2]

MSG_ERR = "There is an error!"
MSG_SUCCESS = "\033[32mCompleted successfully!\033[0m"

# Directories to skip during file traversals. Matched by name, anywhere
# in the tree.
COMMON_EXCLUDE_DIRS = {
    ".git",
    ".vscode",
    ".west",
    "venv",
    "__pycache__",
    "build",
    "distrib",
    "firmwares",
    # upstream-vendored or generated content
    "api",  # cores/arduino/api -> ArduinoCore-API symlink
    "blobs",  # loader/blobs
    "llext-edk",  # variants/*/llext-edk (generated by build.sh)
}


def _git_lines(*args, cwd=None):
    result = subprocess.run(
        ["git", *args],
        check=True,
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    return [line for line in result.stdout.splitlines() if line]


def changed_files(base_ref, diff_filter="ACMR"):
    """List files added/copied/modified/renamed since base_ref.

    Compares the working tree against the merge-base of base_ref and HEAD,
    so it sees committed, staged and unstaged changes alike. Untracked
    files (respecting .gitignore) count as added. Returned paths are
    absolute, so the caller's working directory does not matter.
    """
    merge_base = _git_lines("merge-base", base_ref, "HEAD", cwd=REPO_ROOT)[0]

    files = _git_lines(
        "diff",
        "--name-only",
        f"--diff-filter={diff_filter}",
        "--ignore-submodules",
        merge_base,
        cwd=REPO_ROOT,
    )
    if "A" in diff_filter:
        seen = set(files)
        files += [
            name
            for name in _git_lines(
                "ls-files", "--others", "--exclude-standard", cwd=REPO_ROOT
            )
            if name not in seen
        ]
    return [str(REPO_ROOT / name) for name in files]


def _file_matches(name, extensions, include_names, ignore_names, ignore_suffixes):
    """Decide whether a file name is a check target.

    include_names always match; ignore_names never do. Otherwise the
    suffix must not be in ignore_suffixes and must be in extensions
    (extensions=None matches any suffix).
    """
    if name in include_names:
        return True
    if name in ignore_names:
        return False
    suffix = os.path.splitext(name)[1]
    if suffix in ignore_suffixes:
        return False
    return extensions is None or suffix in extensions


def _excluded(p):
    """True if any path component under the repo root is an excluded dir.

    Only repo-relative components are matched, so a workspace living
    under a directory that happens to be named e.g. 'build' or 'venv'
    does not exclude everything.
    """
    try:
        parts = p.resolve().relative_to(REPO_ROOT).parts
    except ValueError:
        # Resolves outside the repo (e.g. through a symlinked dir such
        # as cores/arduino/api); fall back to the unresolved parts.
        parts = p.parts
    return bool(set(parts) & COMMON_EXCLUDE_DIRS)


def collect_files(
    paths, extensions=None, include_names=None, ignore_names=None, ignore_suffixes=None
):
    """Filter file paths down to existing, non-symlink check targets."""
    files = []
    for path in paths:
        p = Path(path)
        if not p.is_file():
            log.wrn(f"Path not found, skipping: {p}")
            continue
        if (
            _file_matches(
                p.name,
                extensions,
                include_names or (),
                ignore_names or (),
                ignore_suffixes or (),
            )
            and not _excluded(p)
            and not p.is_symlink()
        ):
            files.append(p.resolve())
    return files


class CheckCommand(WestCommand):
    """Base class for rak-* check commands; adds the -v/--verbose flag."""

    def do_add_parser(self, parser_adder):
        parser = parser_adder.add_parser(
            self.name, help=self.help, description=self.description
        )
        parser.add_argument(
            "-v", "--verbose", action="store_true", help="verbose output"
        )
        return parser

    def select_files(self, verbose, **filters):
        """Changed files matching filters, plus the ignored count."""
        paths = changed_files(BASE_REF)
        files = collect_files(paths, **filters)
        if verbose:
            for f in files:
                log.inf(f"Found file: {f}")
        return files, len(paths) - len(files)


def check_files(name, files, check_one, ignored=0):
    """Check each file with check_one and report a pass/fail summary.

    check_one is called with a single file path and must return True if
    the file passes the check.
    """
    if not files:
        log.wrn("No matching files found, nothing to check.")
        return

    log.inf(f"Running {name} on {len(files)} file(s)...")
    failed = sum(1 for f in files if not check_one(f))

    log.inf(
        f"Checked {len(files)} file(s): {len(files) - failed} passed, "
        f"{failed} failed - ({ignored} ignored)"
    )
    if failed:
        log.die(MSG_ERR)
    log.inf(MSG_SUCCESS)


def run_tool(cmd, name, files, ignored=0, fail_msg=None):
    """Like check_files, but each file is checked by an external tool.

    When fail_msg is given, failing files are reported as
    '<fail_msg>: <file>' (for tools silenced with a quiet flag).
    """

    def check_one(f):
        try:
            ok = subprocess.run(cmd + [str(f)], check=False).returncode == 0
        except FileNotFoundError:
            log.err(f"Executable '{cmd[0]}' not found. Please install it.")
            log.die(MSG_ERR)
        if not ok and fail_msg:
            log.err(f"{fail_msg}: {f}")
        return ok

    check_files(name, files, check_one, ignored)
